# Generated by Django 3.2.3 on 2021-07-17 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_support', models.EmailField(blank=True, max_length=50, null=True)),
                ('tech_support', models.EmailField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('hobby', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.PositiveSmallIntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
